name: novelina
description: A Flutter application for reading novels.

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  getwidget: ^7.0.0
  device_info_plus: ^12.1.0
  webview_flutter: ^4.13.0
  intl: ^0.20.2
  http: ^1.2.0
  universal_html: ^2.2.4
  loading_animation_widget: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/stories/

